server:
    port: ${vcap.application.port:1111}   # HTTP (Tomcat) port

# Configure this Discovery Server
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0

 
# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf